== DM571 Unit Test Test
We will use this repository in the lecture and you will be tasked with implementing and solving some assignments


=== Prerequisites

- JDK 8 or higher
- Gradle use `gradlew` wrapper

=== Building with Gradle
Type:

    ./gradlew clean test

Downloaded files (including the Gradle distribution itself) will be stored in the Gradle user home directory (typically *user_home*`/.gradle`).

=== Creating an IDEA project
Just open the project directory with Intelli IDEA and it should auto-detect the project settings.

=== Example Test
[,groovy]
----
include::src/test/groovy/Dm571SpockSpec.groovy[tags=plusOperatorTest]
----

== Assignments

=== First Assignment
Finish the test in this file link:src/test/groovy/Dm571SpockSpec.groovy[Dm571SpockSpec.groovy]:
[,groovy]
----
include::src/test/groovy/Dm571SpockSpec.groovy[tags=lowercaseTest]
----

=== Second Assignment
Finish the test in this file link:src/test/groovy/Dm571SpockSpec.groovy[Dm571SpockSpec.groovy]:
Finish the test using Data Tables in Spock:
[,groovy]
----
include::src/test/groovy/Dm571SpockSpec.groovy[tags=lowercaseTestDataDriven]
----

=== Third Assignment
Start out by removing the `@Ignore` directive in the file link:src/test/groovy/Dm571SpockPersonSpec.groovy[Dm571SpockPersonSpec.groovy]:
[,groovy]
----
include::src/test/groovy/Dm571SpockPersonSpec.groovy[tags=ignore]
----

Then finish the test:
[,groovy]
----
include::src/test/groovy/Dm571SpockPersonSpec.groovy[tags=personTestConstructor]
----

=== Fourth Assignment
Finish the test:
[,groovy]
----
include::src/test/groovy/Dm571SpockPersonSpec.groovy[tags=personTestToString]
----

=== Fifth Assignment
Use link:https://en.wikipedia.org/wiki/Test-driven_development[Test Driven Development (TDD)] to implement a method in the Person class that returns the current age of the person.

== Credits
This repo is very inspired by the https://github.com/spockframework/spock-example[Spock Framework Example Project]

